//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiDashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("apiDashboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al procesar la solicitud, favor de verificar que sea un comando válido..
        /// </summary>
        internal static string REST_Service_Message_ERROR {
            get {
                return ResourceManager.GetString("REST_Service_Message_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso realizado con éxito.
        /// </summary>
        internal static string REST_Service_Message_EXITO {
            get {
                return ResourceManager.GetString("REST_Service_Message_EXITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin información de respuesta!!!.
        /// </summary>
        internal static string REST_Service_NoResultado {
            get {
                return ResourceManager.GetString("REST_Service_NoResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros incorrectos.
        /// </summary>
        internal static string REST_Service_Parametros_Incorrectos {
            get {
                return ResourceManager.GetString("REST_Service_Parametros_Incorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string REST_Service_Status_code_ERROR {
            get {
                return ResourceManager.GetString("REST_Service_Status_code_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string REST_Service_Status_code_EXITO {
            get {
                return ResourceManager.GetString("REST_Service_Status_code_EXITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AVISO.
        /// </summary>
        internal static string REST_Service_Status_response_AVISO {
            get {
                return ResourceManager.GetString("REST_Service_Status_response_AVISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR.
        /// </summary>
        internal static string REST_Service_Status_response_ERROR {
            get {
                return ResourceManager.GetString("REST_Service_Status_response_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXITO.
        /// </summary>
        internal static string REST_Service_Status_response_EXITO {
            get {
                return ResourceManager.GetString("REST_Service_Status_response_EXITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MENSAJE.
        /// </summary>
        internal static string REST_Service_Status_response_MENSAJE {
            get {
                return ResourceManager.GetString("REST_Service_Status_response_MENSAJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO AUTORIZADO.
        /// </summary>
        internal static string REST_Service_Status_response_NOAUTORIZADO {
            get {
                return ResourceManager.GetString("REST_Service_Status_response_NOAUTORIZADO", resourceCulture);
            }
        }
    }
}
